
version: "3.9"

services:
  app:
    build: .
    container_name: snackr_app
    ports:
      - "3001:3001"
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/snackrdb
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
